name: ASP.NET 6.0 API StyleCop Check

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Install StyleCop
      run: dotnet add package StyleCop.Analyzers --version 1.1.118

    - name: Build and Analyze
      run: dotnet build
